### ISSUE TITLE
Question: What --password flag do?

### ISSUE THREAD

**Issue by pleshevskiy** [brxken128/dexios#100]
I tried to figure out what the -p (--password) flag for the `encrypt` and `dencrypt` subcommands is for, but could not find its use in the code. If we don't pass a key file or env, it always falls back to user input.

**Comment by brxken128** [comment]
Where are you seeing the flag? This was deprecated with the new key handling/restructuring that was added in v8.7.0, maybe I missed some of it.

**Comment by pleshevskiy** [comment]
You can see it in the help, because... 

- `encrypt` - https://github.com/brxken128/dexios/blob/master/dexios/src/cli.rs#L71
- `decrypt` - https://github.com/brxken128/dexios/blob/master/dexios/src/cli.rs#L144

**Comment by brxken128** [comment]
Thank you! I'll add this to the todo list. I'd like to mention that a refactor of `cli.rs` is due, as I am nowhere near happy with the structure of it.

**Comment by pleshevskiy** [comment]
I think the [structopt](https://docs.rs/structopt/latest/structopt/) is more suited to your mechanics. Many options are repetitive and you could reuse them. :thinking:

**Comment by brxken128** [comment]
I'm undecided between `structopt` and clap's derive API - they're both quite similar I believe. The derive API would likely be easier to migrate to, as we're already using `clap` within Dexios.

**Comment by pleshevskiy** [comment]
I missed this update from `clap`. Took one look and it really would be the best solution!

**Comment by brxken128** [comment]
Those were my thoughts! It looks great and I'm not too sure why I didn't go with it from the start - it'll sure look a lot better than what we currently have.

**Comment by pleshevskiy** [comment]
https://github.com/clap-rs/clap/blob/master/docs/FAQ.md#how-does-clap-compare-to-structopt

**Comment by brxken128** [comment]
> https://github.com/clap-rs/clap/blob/master/docs/FAQ.md#how-does-clap-compare-to-structopt there are actually the same

That explains a lot! Thank you.
