### ISSUE TITLE
[BUG] --auto parameter 

### ISSUE THREAD

**Issue by Kispisti** [brxken128/dexios#103]
Maybe i missed something or what ,but....:

c:\Users\karbantartokac\Desktop\z>dex encrypt --auto 1.dat 1.enc
-960996e0m Your generated passphrase is: September
←[36mℹ←[0m Using XChaCha20-Poly1305 for encryption
←[36mℹ←[0m Encrypting 1.dat (this may take a while)
←[32m✔←[0m Successfully hashed your key [took 2.96s]
←[32m✔←[0m Encryption successful! File saved as 1.enc [took 0.60s]

c:\Users\karbantartokac\Desktop\z>dex decrypt 1.enc 1.kii
Password: September
←[36mℹ←[0m Using XChaCha20-Poly1305 for decryption
←[36mℹ←[0m Decrypting 1.enc (this may take a while)
←[32m✔←[0m Successfully hashed your key [took 2.85s]
Error: Unable to decrypt your master key (maybe you supplied the wrong key?)

Am i do something wrong ?!

**Comment by brxken128** [comment]
It seems so. `September` is not a valid password that Dexios will generate - have you tried using "Windows Terminal"? The icons aren't rendering correctly which suggests you're using `cmd` - this is advised against throughout the OS-specific documentation.

I'll give it a shot using `cmd` and see if I can reproduce shortly.

**Comment by Kispisti** [comment]
I use win10 ,on a restricted user account. Yes. Cmd.exe.

Real "screenshot" : :D

![20220704_114416](https://user-images.githubusercontent.com/107638197/177131496-5edfa3d4-bad2-456d-9138-5f99546e5673.jpg)

**Comment by brxken128** [comment]
`September` is not a key that `--auto` should be generating, so either this is an issue with `cmd.exe` output (which I have mentioned in the docs, [here](https://brxken128.github.io/dexios/Installing-and-Building.html#windows)), or something is broken on Windows specifically. I'll load up a Windows VM and take a look.

Is Dexios installed via cargo?

**Comment by brxken128** [comment]
![image](https://user-images.githubusercontent.com/77554505/177132517-ca7abcb5-67ce-4b17-ad37-57a1126b12f7.png)

This works for me, within `cmd` as well as the Terminal application.

What version of Windows are you using? Have you tried the terminal application?

**Comment by Kispisti** [comment]
No,precompiled latest binary.

**Comment by brxken128** [comment]
I was able to reproduce this issue with the precompiled binary, but installing through `cargo` makes everything work flawlessly. I'll take a deeper look into this, but for now I'd recommend not using `--auto` on Windows with the pre-compiled binary (until this issue is fixed).

**Comment by Kispisti** [comment]
Doesnt work even in Windows PowerShell. Btw thank you!

**Comment by brxken128** [comment]
> Doesnt work even in Windows PowerShell. Btw thank you!

I know. I'm not too sure what's causing this issue, as I'd expect pre-compiled binaries to behave the same way.

**Comment by Kispisti** [comment]
Tried 3rd party terminal ,called Console2 from sf.net. Doesnt work,too.... (use it daily @ home)

**Comment by brxken128** [comment]
Yeah - it's an issue with the pre-compiled binary itself. I'm not sure why, or how. I need to take a deeper look into it, but I'll remove the pre-compiled binary for now.
