### ISSUE TITLE
Enable large file (>4Gb) support for pack

### ISSUE THREAD

**Issue by Rust-Galt** [brxken128/dexios#12]
in pack.rs add large file option to enable large files.
app crashes when it encounters large files.
`let options = FileOptions::default()
        .compression_method(zip::CompressionMethod::Bzip2)
        .compression_level(Some(6)) // this is the default anyway
        .large_file(true) // enables support of files >4Gb at a small size penalty
        .unix_permissions(0o755);`

**Comment by brxken128** [comment]
Good call, I didn't test large files just yet. Glad you picked it up! :)
