### ISSUE TITLE
Question: Are words with digits valid?

### ISSUE THREAD

**Issue by pleshevskiy** [brxken128/dexios#124]
I found [1](https://github.com/brxken128/dexios/blob/master/dexios/src/subcommands/wordlist.lst#L7748), [2](https://github.com/brxken128/dexios/blob/master/dexios/src/subcommands/wordlist.lst#L6640), [3](https://github.com/brxken128/dexios/blob/master/dexios/src/subcommands/wordlist.lst#L2528), [4](https://github.com/brxken128/dexios/blob/master/dexios/src/subcommands/wordlist.lst#L2009) words with digits. Are they valid? Do they need to be removed?

**Comment by brxken128** [comment]
Oh, that's my bad! I thought I fully removed the indexes, but evidently not. They could do with being removed please :)

vscode was fixed on Void so I can get back to finishing V5!
