### ISSUE TITLE
[COSMETIC] Uniformity between module declarations

### ISSUE THREAD

**Issue by brxken128** [brxken128/dexios#139]
I've noticed that we use both ways of defining modules throughout the codebase:

* a `mod.rs` file
* a file that matches the name of the subfolder, that declares modules within it (e.g. `subcommands.rs`, and the `subcommands/` dir)

According to the [Rust book](https://doc.rust-lang.org/reference/items/modules.html#module-source-filenames), it's encouraged to use the 2nd option. I don't mind either, I was just wondering if anyone had any objections to me changing it.

**Comment by pleshevskiy** [comment]
I read the book a long time ago and missed this innovation) Although I'm more accustomed to the structure with `mod.rs`, because it's easier to find the right file, but I'll adjust)

**Comment by brxken128** [comment]
> I read the book a long time ago and missed this innovation) Although I'm more accustomed to the structure with `mod.rs`, because it's easier to find the right file, but I'll adjust)

No worries my friend :)
