### ISSUE TITLE
[FEATURE] Implement `zeroize` for `vec_to_arr()`

### ISSUE THREAD

**Issue by brxken128** [brxken128/dexios#162]
In order to maintain cryptographic hygiene surrounding encryption keys, we need to use `zeroize` in all places they touch.

`vec_to_arr()` is used directly while decrypting master keys, so it needs to be "sanitised".

I don't mind figuring out a way to implement this myself, as it seems simple enough (don't quote me on that!)

**Comment by pleshevskiy** [comment]
The new (relatively) stabilized features of Rust inspired me to completely rewrite one of my creations) I even wrote a simple fun calculator on environment variables (https://github.com/pleshevskiy/itconfig-rs/blob/redesign/examples/calc.rs)))). If you don't mind, I can start working on this task after the weekend)

**Comment by brxken128** [comment]
> The new (relatively) stabilized features of Rust inspired me to completely rewrite one of my creations) I even wrote a simple fun calculator on environment variables (https://github.com/pleshevskiy/itconfig-rs/blob/redesign/examples/calc.rs)))). If you don't mind, I can start working on this task after the weekend)

Of course! Good luck with your project, and if you need any help feel free to ask. I had a quick peek and it looks pretty cool. No rush here, there's still more than enough for me to work my way through :)

Following up from the other day, I started using the `helix` editor as opposed to vscode, and I couldn't be happier. It's written in Rust and has support for all of the features I'm after, and I find it pretty easy to use. I know it's not `neovim`, but it's better than what I had before so :)

**Comment by pleshevskiy** [comment]
@brxken128 do you have any messenger?) [simplex](https://github.com/simplex-chat/simplex-chat), matrix, else? It will be better than flooding into your repo))))))))))

**Comment by brxken128** [comment]
> @brxken128 do you have any messenger?) [simplex](https://github.com/simplex-chat/simplex-chat), matrix, else? It will be better than flooding into your repo))))))))))

I do! `@brxken128:matrix.org`, although I've never had the chance to use it before :)
