### ISSUE TITLE
[BUG] secure_erase not overwriting end of files not a multiple of 512

### ISSUE THREAD

**Issue by h4l7** [brxken128/dexios#38]
**Describe the bug**
In `src/erase.rs:32`, the `secure_erase` function does not write random bytes for the remainder of the given `input` if the size of `input` is not a multiple of 512 bytes.
For example, if we have a file of size 20648, we iterate `(data.len() / 512)*512 = 40` times. This means we write `40*512 = 20480`, leaving `20648 - 20480 = 168` bytes at the end of `input` unmodified on disk.

**To Reproduce**
`dexios erase <input>` for file not a multiple of 512 bytes.

**Expected behavior**
Modify behavior of inner loop at  `src/erase.rs:31` to write the residual bytes after executing the `for i in 0..data.len() / 512 { ... }` loop.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
If I've made a mistake in my assessment of the issue, please correct me.

**Comment by brxken128** [comment]
Your assessment is correct!

This was something I wrote down as an area of concern in my notes, and I did a bit of testing in the Rust Playground (to no avail).

I'm free later to fix this, it shouldn't take long to figure something out. Thank you for the report.

**Comment by brxken128** [comment]
I believe 3740a95620137ab6fe5d3f3ae8b0c846ed393417 fixes it.

If the file is less than 512 bytes, it'll now just dynamically create a buffer of that size. Otherwise, it'll write all 512 byte "blocks", and create a buffer dynamically to reach the end of the file.

Thank you for the bug report!
