### ISSUE TITLE
DexiosGui

### ISSUE THREAD

**Issue by Antidote1911** [brxken128/dexios#45]
Hello brxken128,
I would like to present you [DexiosGui.](https://github.com/Antidote1911/dexiosgui)

For fun, I have make some modifications to my crypto tool [Cryptyrust](https://github.com/Antidote1911/cryptyrust) for use it with Dexios format. For now, It only implement the "streamMode".
It is compatible with win/nix. With Light/Dark skin, config saving...

My [Cryptyrust](https://github.com/Antidote1911/cryptyrust) include big portions of Dexios code. I have included THX to you in the readme.

Suggestion: For the future, it will be excellent if Dexios was released in the form of lib. Separate the cli app and the core crypto (like my [Cryptyrust](https://github.com/Antidote1911/cryptyrust)) allow to use your format in multiple app.

Sorry for my bad english ;)

Thank for all your work on Dexios recently.

**Comment by brxken128** [comment]
This is incredible work!

I starred Cryptyrust the other day - I recall the two of us having similar issues selecting AEADs idiomatically and I liked the functionality of your program.

I had plans in the future to split Dexios into three parts: a `dexios-core` encryption/decryption/header handling library, `dexios` for CLI and then `dexios-gui` for the GUI side of things. I believe I mentioned this briefly in #32 :)

Honestly you've done a great job adapting it, and creating the GUI - my hat goes off to you.

In light of this, I'm tempted to work on splitting Dexios into at least `dexios-core` a bit sooner than I thought, as this will help your project out too. This will have to be once #44 is complete, as the code base is going to change majorly. The refactor will help with splitting the crates as well.

Thank you so much for this cool project, and I'll test it out when I can! Amazing work :))
