### ISSUE TITLE
Cascaded ciphers

### ISSUE THREAD

**Issue by Kispisti** [brxken128/dexios#75]
Hello!

Do you plan to add cascaded cipher support?
For example :xChaCha20-Serpent-Twofish? (256 bits)
IMHO its a pretty hard combo...

OTOH nowadays AES is a no-go....  Ok,its more than enough,but there are more secure algos,like above.
Overall personally i dont trust Rijndael....

**Comment by brxken128** [comment]
I don't think I'll be adding this, unless there's others that would like to see it.

Cascading ciphers were highly recommended in the days of DES, but the issue they solved isn't really around anymore. XChaCha20-Poly1305 is regarded as secure, and so are the other AEADs that we use.

I get the inherent distrust regarding Rijndael, but I don't believe the way around it is to add further complexity to the alternatives.

I'll leave this open for discussion.
