### ISSUE TITLE
Custom/better compression

### ISSUE THREAD

**Issue by Kispisti** [brxken128/dexios#76]
Hello !

Similar apps ,like yours ,PicoCrypt,etc,only supports ZIP-compression internally.
It would be nice to implement ZSTD...
What do you think about it?

**Comment by brxken128** [comment]
Considering our use-case, I think this could be fine. Usually, compression with encryption isn't too recommended - but that's only in cases where it's likely that an attacker has control over some of the input data.

I may make it selectable (with a `-c` switch or similar), but not the default. I'd also like to research the differences between compression algorithms available, and find the most suitable.

**Comment by brxken128** [comment]
This was implemented in #79 - it uses a ZSTD compression level of 3, and you may enable it with the `-z` switch when packing files.
