### ISSUE TITLE
[FEATURE] Encrypting a Directory

### ISSUE THREAD

**Issue by brxken128** [brxken128/dexios#8]
I personally do not plan to add support for encrypting/decrypting based on a `glob` pattern (at this moment in time anyway). I've tried before and could not get a user-friendly implementation going.

What I do think could be valuable is encrypting a singular directory. My plan was to encrypt each file in the directory as normal (so they each have their own salt/nonce), and then to compress them into a `tar` or `zip` file. I'm leaning more towards `tar`.

Then, that compressed file will be encrypted once again, this time with *ideally* a different key provided by the user, or the same key could work but only with a different salt.

If the keys were different, a brute force attack would take considerably longer. With the same key **and different salts** (this is the default implementation in Dexios anyway), an attacker just has to find one key and all of the files will be decrypted. I guess functionality should be added for both use cases.

As far as I'm aware, there are no cryptographic downfalls to encrypting twice with **different** nonces in this case. That, and the compression imposed by `tar`ing the files should be more than enough, although I'd definitely inspect output files before releasing this feature.

I would suggest file-name encryption also, but if the whole `tar` file is encrypted anyway, I don't see the point.

You may track the progress of this on the `directory-encrypt` branch - I plan to work heavily on this feature and I don't see it taking more than 2/3 days - most of the groundwork has been laid out.

Appropriate GA tests will be added also.

**Comment by brxken128** [comment]
I think a recursive option could be helpful as well.

**Comment by brxken128** [comment]
Here's what I have so far, it's getting late so I'll pick this up tomorrow.

e67f606a2456d4aa66d5c8e7daf1a4e33b2e6f0b

**Comment by Rust-Galt** [comment]
I think encrypting files separately would only be useful if access to those single files is wanted. And if the whole .tar gets encrypted we don't really save much computing. 
I don't see a security benefit in using multiple nonces. Nonce reuse is the main (very unlikely, if crypto_random) danger and even more unlikely for issues with a random salt for the hash. So even with the same user passphrase, both nonce and salt need to be reused and when chosen randomly this should be extremely unlikely.
 
There is no fix for weak user passphrases/keys. Key stretching with argon2id seems like an excellent choice already. I can only see one way to possibly increase the safety by **making the argon2 hash parameters more costly**! 

_So it is a question of, what is the desired outcome of the new feature?_

**Feature1**: I think the feature **"Encrypt a whole folder at once into a single file"** could be fulfilled by:
Encrypt: folder -> tar(folder) -> dexios(tar(folder))
Decrypt: dexios(tar(folder)) -> ar(folder) -> folder

_No issues with handling of multiple keys/nonces..._

**OR**

**Feature2**: **Encrypting all files in a folder recursively** sounds like a different feature:  
folder(file_0, file_1, folder?(recursion?), file_n) -> folder(dexios(file_0), dexios(file_1), folder?(skip/recursion?), dexios(file_n)).

I like _Feature 1_. Which leads to the question if compression should be a feature too but likely outside of the scope of the app. I like the simple file structure of the output, just what is needed. A tarball can preserve all file attributes/paths/... so the app does not have to handle those things and be data agnostic in a sense.

I don't know but think that enum cloning leads to no overhead at all, tiny amounts of data that likely gets optimized away.

**Comment by brxken128** [comment]
> I think encrypting files separately would only be useful if access to those single files is wanted. And if the whole .tar gets encrypted we don't really save much computing. 
> I don't see a security benefit in using multiple nonces. Nonce reuse is the main (very unlikely, if crypto_random) danger and even more unlikely for issues with a random salt for the hash. So even with the same user passphrase, both nonce and salt need to be reused and when chosen randomly this should be extremely unlikely.
>  
> There is no fix for weak user passphrases/keys. Key stretching with argon2id seems like an excellent choice already. I can only see one way to possibly increase the safety by **making the argon2 hash parameters more costly**! 
> 
> _So it is a question of, what is the desired outcome of the new feature?_
> 
> **Feature1**: I think the feature **"Encrypt a whole folder at once into a single file"** could be fulfilled by:
> Encrypt: folder -> tar(folder) -> dexios(tar(folder))
> Decrypt: dexios(tar(folder)) -> ar(folder) -> folder
> 
> _No issues with handling of multiple keys/nonces..._
> 
> **OR**
> 
> **Feature2**: **Encrypting all files in a folder recursively** sounds like a different feature:  
> folder(file_0, file_1, folder?(recursion?), file_n) -> folder(dexios(file_0), dexios(file_1), folder?(skip/recursion?), dexios(file_n)).
> 
> I like _Feature 1_. Which leads to the question if compression should be a feature too but likely outside of the scope of the app. I like the simple file structure of the output, just what is needed. A tarball can preserve all file attributes/paths/... so the app does not have to handle those things and be data agnostic in a sense.
> 
> I don't know but think that enum cloning leads to no overhead at all, tiny amounts of data that likely gets optimized away.

I agree - I don't know why I was so caught up on encrypting twice.

On the branch, I have a directory indexer in place, with the option for recursion. (not tested yet but I don't see what wouldn't work)

For recursively encrypting, we'd only have to create the tar and then encrypt, just as we would with a single directory, so I think that should be fairly trivial anyways.

I have no experience with the `tar` crate but I do with `zip`, so I'm hoping they're somewhat similar.

With `zip` you had to get a list of directories, and a list of files. You'd recreate the directory structure within the archive, and then populate it with the files. My directory indexer is suited to this, but it's rather simple and can easily be adapted to other needs.

**Comment by Rust-Galt** [comment]
I will not work on anything quiet yet. Just sharing some thoughts. 
My first though would be to just use the Linux utility "tar" as it will be installed in most cases?, supports recursion and all file handling and then write tar to a file and then overwrite it by encrypting it, is that possible or use a temporary file and clean it up.
Of course it is more elegant to integrate it in the app directly. The procedure for zip sound like it should apply for tar as well. 

A different feature would be encrypt all files in a folder. No tarball involved. Results in a folder of encrypted files.

**Comment by brxken128** [comment]
> I will not work on anything quiet yet. Just sharing some thoughts. 
> My first though would be to just use the Linux utility "tar" as it will be installed in most cases?, supports recursion and all file handling and then write tar to a file and then overwrite it by encrypting it, is that possible or use a temporary file and clean it up.
> Of course it is more elegant to integrate it in the app directly. The procedure for zip sound like it should apply for tar as well. 

Interfacing with the Linux tar utility would give less control, and it might pose issues FreeBSD compatibility, so I'd prefer to use a dedicated crate.

> A different feature would be encrypt all files in a folder. No tarball involved. Results in a folder of encrypted files.

As for this, I have tried to implement it in the past, however I couldn't get a user-friendly enough implementation going. It was all just a bit clunky, but I think it's possible now.

It would probably sit under a different mode in `clap` to the tar functionality, and I feel as though the tarball would have more use as it creates a so called "black hole" in regards to the directory structure, file names, etc. It also makes things more portable.

In regards to the tarball feature, I think a `--exclude=` argument would be helpful, similar to `rsync`.

I think we'd have to get all of the --exclude values, and push them into a Vec (within main.rs), and when we're indexing the directory we should compare the names, and ignore them completely if they're excluded.

It's still quite early here but I plan on getting to work shortly - I have most of it planned out in my head so I don't expect it to take too long at all.

**Comment by brxken128** [comment]
The `tar` crate does not include compression, and hasn't been updated in 5 months (it doesn't seem too actively maintained). I may have to look into using the `zip` crate

@Rust-Galt

**Comment by Rust-Galt** [comment]
I like the idea of: `folder -> dexios(folder) -> folder`
So encrypt + decrypt combined does "nothing" in a sense. 

So zip is merely a "tool" a container to transport the filesystem. I guess there are zip options to not compress at all if we want to safe CPU ressources?

After `  let mut data = Vec::new();
            file_reader.read_to_end(&mut data)?;
            zip_writer.write_all(&mut data)?;`
Is there a method to close the file in the file reader. Maybe read to end still waits for us to continue reading...
 `too many open files` is likely the filesystem crying.
Will get to the pc later and start looking more at things later.

**Comment by brxken128** [comment]
I have fixed the `too many open files` issue - I was recursively reading the same directory instead of the other detected directory.

File indexing seems to work a charm now.

**Comment by brxken128** [comment]
> > dexios compress -r encrypt dir/ file.zip
> 
> Not sure if "compress" is the best term. As the implementation of how we encrypt a folder should not matter to the user. So maybe a pack or folder option that has a compression flag that can be used? So when the encrypt method detect it is a folder error and tell about the directory option? Or ask if we want to proceed with the whole dir? So keeping the pattern: `dexios -e/-d in out` and then for directories require it to be specified `dexious -eP in_dir out` (Pack? or Dir?)
> 
> > File indexing seems to work a charm now.
> 
> Nice!
> 
> So app(dexios) I now either want to encrypt, decrypt or help. At least that is what I think. I know just minor stuff. Maybe you already embarked on the clap configuration... so maybe not so minor

I could pretty easily change `compress` to `pack`, but if we remove the subcommand as a whole, it'd be a lot harder to manage compression levels, recursive options, or excluding a pattern. It's possible, but I think it'd become less user-friendly in the grand scheme of things.

I'll do it now though, as my encryption implementation is at a place I'm happy with.

**Comment by brxken128** [comment]
I just tried, and I honestly don't think it's worth it - handling all of the possible switches and such becomes a mess.

I wouldn't mind attempting to add it again in the near future, but I think `encrypt`, `help`, `decrypt` and `pack` are a pretty minimal amount of subcommands, all things considered.

**Comment by Rust-Galt** [comment]
Seems very reasonable. Nice. Should merge well. If I fork to maybe get a pull. I prefer master branches to browse in :D

**Comment by brxken128** [comment]
I'm going to implement more tests and such too, but I feel as though this will be a pretty solid feature.

selecting a branch manually is never fun LMAO
