### ISSUE TITLE
File is created in filesystem while using the -b benchmark flag [BUG]

### ISSUE THREAD

**Issue by Rust-Galt** [brxken128/dexios#9]
**File is created in filesystem while using the -b benchmark flag**
When using an input file larger than memory mode limit a 0kb is created in the filesystem.

**To reproduce**
Command to reproduce this behaviour:
In empty folder
create testfile then
`dd bs=10M seek=1 of=testdata count=0`
`./dexios -eb testdata out`

Should be a very simple fix

**Comment by brxken128** [comment]
This is on the todo list (can be found in the wiki) - it's a rather trivial fix.

I'll release a patch shortly.

**Comment by Rust-Galt** [comment]
Excellent! Will make sure to read the ToDo properly next time.

**Comment by brxken128** [comment]
> Excellent! Will make sure to read the ToDo properly next time.

It's not an issue, I'd pushed it back on my list mentally and I probably should've tackled it sooner :)

**Comment by brxken128** [comment]
I was originally going to wrap it in `Option<File>`, but I realised we'd run into possibly uninitialised variable issues and such, so an `enum` based approach seemed more suitable to me.

I believe performance is the same, and with the `-b` switch I can see that most of the tool's performance is down to disk speed, and not Dexios itself, which I am very happy about.

**Comment by brxken128** [comment]
It passes the tests, and I have not noticed any anomalous performance results, so I'll consider this fixed.

Thank you for the report! :)
