### ISSUE TITLE
Some small ideas

### ISSUE THREAD

**Issue by Kispisti** [brxken128/dexios#94]
Hi !

At first ,thanks for Dexios ! It is a cool ,great job.

1. - Well ,it would be nice to integrate it into Explorer/context menu in Win (at least when decrypt) ,but i cant do it. An option is missing to tell Dexios to open a browser window for target folder designation. Can you do it ? Is it a viable idea ?

2. - ZSTD : I hope its not too late ,but a customizable compression setting/level would be nice ,too.

3. - Two weeks ago you rejected to add SERPENT into cascade mode. But now i please you again to reconsider it. Not for a permanent cascade mode ,just an additional option to use ,just like in P__oC___t. (It has no CLI ,drag and drop based ,i dont use it. Unconvenient for me)

All the best for you!

**Comment by brxken128** [comment]
I apologise to do this again, but I still don't think cascaded ciphers are worth it. I won't implement this myself, but you are free to do so (or you can just encrypt your file once with XChaCha20-Poly1305, and another with AES-GCM/Deoxys).

It would add some rather unwarranted complexity, and the chances of our implementation being broken are significantly higher than heavily-scrutinized XChaCha20-Poly1305 (or similar) being broken.

You can view the audit for the XChaCha20-Poly1305 and AES-GCM libraries that we use [here](https://research.nccgroup.com/wp-content/uploads/2020/02/NCC_Group_MobileCoin_RustCrypto_AESGCM_ChaCha20Poly1305_Implementation_Review_2020-02-12_v1.0.pdf).

If we're considering this level of paranoia, I'd probably start thinking about securing your data from other angles. Starting with your host OS would be a large one, as it's more likely that you'll be victim to a keylogger than an extremely well-regarded cipher be broken.

Thank you for your suggestions, and if you'd like to offer any counter-arguments to my decision then please feel free to do so. I'll leave this open for now.

**Comment by Kispisti** [comment]
1. - misunderstand me. I dont need a GUI ,etc. Only a switch to pop up a browser window if i want to decrypt. I can integrate it myself to the context-menu.:)

2. ZSTD : Great!!!

3. Understood ,forever!:)

**Comment by brxken128** [comment]
> 

I don't think I follow. As in a browser window to browse your files, so you're able to select one for decryption?

**Comment by Kispisti** [comment]
I can integrate the whole decryption cmd line to context menu ,as i want. It ok.
What i want is ,for exaple 

Dexios.exe decrypt mycrypteddata.xxx -browserwindow

Executing this ,pops up a browser window to designate output dir... its nice ,when output dir has many-many chars. thats all. Is it viable for you?

Sorry ,english is not my native language...

**Comment by Kispisti** [comment]
Before i forget : can you add a process percentage display or progress bar?

**Comment by brxken128** [comment]
> Before i forget : can you add a process percentage display or progress bar?

I can. I have added this before, in a very basic testing version (this is while I was trying to even get stream encryption to work). I think there were some slowdowns with fast machines and large files, due to the amount of time spent updating the progress bar. Maybe every 4~ STREAM blocks could update.

**Comment by brxken128** [comment]
> > Before i forget : can you add a process percentage display or progress bar?
> 
> I can. I have added this before, in a very basic testing version (this is while I was trying to even get stream encryption to work). I think there were some slowdowns with fast machines and large files, due to the amount of time spent updating the progress bar. Maybe every 4~ STREAM blocks could update.

I'll add this in the core library, gated behind a `visual` feature. It won't be anytime too soon, as I have a holiday coming up and I'm trying to relax.
