### ISSUE TITLE
[FEATURE] Support for Multiple Languages

### ISSUE THREAD

**Issue by brxken128** [brxken128/dexios#98]
I think a good starting point would be to add:

* English
* Russian
* French

(as a minimum)

This will be a *very* large task, and will require a lot of re-writing and translating.

I have a bit of knowledge regarding both Russian and French, but my translations likely will not be 100% accurate.

**Comment by pleshevskiy** [comment]
First of all, I think we should create a basic structure for translations and choose the default language (Eng). Then we can translate to other languages :) And I can help with Russian.

**Comment by brxken128** [comment]
This was the plan, I just created a branch not too long ago.

I think a macro to print strings would be ideal, and that macro checks the locale of the host computer and looks up the translation. If it's not added, default to English.

We'd probably need to refactor the printing of things, such as moving file names+additional info to the end of the text - there's probably too many factors throughout languages otherwise.

**Comment by pleshevskiy** [comment]
I think it's better to do without a macro. :man_shrugging:  The macro will add chunks of code every time we place it. And there is not always a rational side to it) I prefer to avoid it if possible

**Comment by pleshevskiy** [comment]
But a macro can help to assemble our beautiful structure into a small call

**Comment by brxken128** [comment]
Going to close this for now. Dexios doesn't have too many command-line outputs (as of #208), so I think most of the work would be on `clap` definitions (and maybe the docs/readmes).
