### ISSUE TITLE
[BUG] Dexios doesn't erase the compressed file on failure.

### ISSUE THREAD

**Issue by pleshevskiy** [brxken128/dexios#99]
**Describe the bug**
I want to pack my directory and Dexios doesn't erase the temporary file on failure.

**To Reproduce**
Preface: You have `data` directory with some files.

Option 1:
  - Run `dexios pack -py data data.enc`
  - Dexios will ask you for your user password, but press `Ctrl+C` (or `Cmd-C` on Mac)
 
Option 2:
  - Run `dexios pack -pyk not_exist.txt data data.enc`
  - Dexios cannot find keyfile and will show error.

**Expected behavior**
Dexios doesn't pack my folder and doesn't create the temporary file (or erase it after fail).

**Actual behavior**
Dexios doesn't pack my folder but creates the temporary file `data.enc.xxxxxx`

**Screenshots**

```bash
pc:~/finance$ ll | grep enc
-rw-r--r--  1 user user 552549 business.enc
-rw-r--r--  1 user user   8125 family.enc
pc:~/finance$ dexios -py business business.enc
ℹ Creating and compressing files into business.enc.HbSr3HzN
ℹ Traversing business
✔ Compressed 3 files into business.enc.HbSr3HzN! [took 0.00s]
Password:
Error: Unable to read password

Caused by:
    Error reading password from terminal
pc:~/finance$ ll | grep enc
-rw-r--r--  1 user user 552549 business.enc
-rw-r--r--  1 user user 552405 business.enc.HbSr3HzN  <<<<<
-rw-r--r--  1 user user   8125 family.enc
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.4

**Comment by brxken128** [comment]
I am aware of this issue, and it has tripped me up in the past while testing (due to the amount of residual files).

Thank you for opening this, I was going to get around to it at some point - I'm just not too sure of the best way to solve it. Maybe pack/unpack mode will require some manual error intervention, so we can delete the temporary file before exiting.

I'll take a look into it properly in the morning, as it's rather late where I am.

Thank you!

**Comment by pleshevskiy** [comment]
It may be most correct to divide it into a "validation phase", a "setup phase" and a "build phase". The validation phase will check if the data we want to pack exists. The setup phase will ask for additional data in our case the password. If everything is successful, in the last build phase we will already create a temporary archive and directly pack.

**Comment by brxken128** [comment]
> It may be most correct to divide it into a "validation phase", a "setup phase" and a "build phase". The validation phase will check if the data we want to pack exists. The setup phase will ask for additional data in our case the password. If everything is successful, in the last build phase we will already create a temporary archive and directly pack.

I think this would be ideal, although there's still room for error. A common error is one also regarding symlinks that point to no valid path. This would be impossible to detect without traversing the directory beforehand, and then another while actually packing the files.

I'll probably need to skip all symlinks entirely.

**Comment by pleshevskiy** [comment]
If you don't mind, I would help you with this issue 🧐

**Comment by brxken128** [comment]
> If you don't mind, I would help you with this issue 🧐

That'd be great! I'm taking things easy over the next few days, as it's a holiday and I'm trying to relax a little lol

Thank you 😃
